
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0NmU1YmViMi1jNDM0LTRhNDAtOGVkMC02YWUwMTg5YjY0ZDUifQ.BbIXSvDKfn8v-FgJjBQzLbFkdrKUtBmTrrruaqf0IuE',
]


url = 'http://10.242.6.92:6600'
