
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJhMDU2N2ZhYi0wODkxLTRmZGUtYjY4My0wZGU2MmNkNGQ5NWYifQ.2ZHQlGMiDDoUfRcNxp8CJZ2ZJPgBb9ancY3fJUBRs-8',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJlYjAzOGZmNS04MzE1LTQ1NmEtYTRmYi02MWY4YzBlY2UyNzcifQ.zC6dDTzxKakIRrImlcfaTPRlT7xEWrMnidmXR6SGgmE',
]


url = 'http://10.102.21.141:6600'
