
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0M2UwM2RmNC1iODAzLTQwYzQtYmI1NC03NWZhM2FlNzFiOGYifQ.LKN9lcjx_nScdi8VG1364cTtfLFfA7X8090expQxtnw',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI3ZTY5MDc5OC1iYTc1LTRiNDEtYTdjYy00ZjNiMzRkNjM3NTIifQ.7DnaH023Hr8UxJjsC2KRt-pDgwDlJ6sdxrNTKVW5Pog',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIzNzUxZWFiYS1iNDFiLTQxY2ItOWVmOS01NWY2ZWQ5OTA2ZjQifQ.mFerk9YhXpaFf0Yj6Dh5yWn3Ko0poua6u2bebVH81aw',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJhYjM1NWEwYS05MTczLTQxMWUtYjkyNS02MjIwNjg3MWEyYzYifQ._rrEeeNCVrZRT_61zFGT7GaRjh-AmVI87LwFMnBL9aw',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJiMDRmOTlmNC00ZDUzLTQ4NjAtYTliZC0zZjY0ZTY0MjRhMjEifQ.Oy05hXZqJ4EAk-a5z5XvGqyF5pnqc1-VuqDATLS6dhQ',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJlYzQ4NjJjMS0xZWYyLTQxMjUtOTE1Zi02MmQ1MzZiMmM4MzgifQ.iBpfQPCz_9GDF_WMqvRrKgZYJHs2EcmCi5RY2MWh_o4',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJmZjQ4MGYwYy05MmVmLTQ4YWMtYWZiYS00NzkzMTcyMzcyMGEifQ.liyu2ETeH95RF7nNvWKxjiiWdvTT3NnU2X66Khaa4RY',
]


url = 'http://10.102.21.141:6600'
