
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1N2U0N2M0OC0xM2Y2LTQ5NjItYjUxMS03NjZjZjNjOGNlMDMifQ.J4GW97taOvAH-KNHRKlTODMpInkKZkyRMOm_61kPT-Q',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI4NGM0NmY1MS1jZGMwLTRlMzAtYTllYy1iZTZiYTQzN2UxNTYifQ.58G0WEhZobbiFAuwjFqhJy1xpejbxUs2JX1UKKpBSV8',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI5ZWY1MmYxZS01NDNhLTRjMWUtOTAzZC0xODdhYmExMDdiZmQifQ.tgZ618afqBiD323in8fjHTB9ypuZapCdrMVGgVbSFcE',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIxZGJjYjQxNS0zNjc3LTRmOGMtYTRkNy0xY2MxZDBiNDc2MjIifQ.9RB3wga-eusgZjPDOJBVH-LkpyreYcVKkPKEiXPYI-k',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIzNDA3NzFjMi0yMTlmLTRiMDgtOTc0NS00MWNmMTVmM2NlZjgifQ.Qi0Z3m4rjdVfSb7z4Cz7jM-stXg9Mn7mjxE3ZPRAZhk',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjNDQzNjgyMi02ZjE0LTQxNzMtODIxNS01M2FjMmQ3NmFiMDIifQ.wazg-PgdEYeA-wV2aw5BJZJKOT6ZSIc7SHEv5K59UF8',
]


url = 'http://10.102.21.141:6600'
