
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI2YTNkYjlhYi03YzQ3LTQ0ODItODJlZS1jNGFjY2RhZjhlY2EifQ.vXOLwerRfNzX0XkHk5TlRAXYdm3vvGVFuxaUasfrkmg',
]


url = 'http://10.102.21.141:6600'
