
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI5MDgzMmNjNS0yNDZlLTQ1NDgtYjhkNC1jY2MxZDI5NjFhNjIifQ.D7D66NwJoL3cYGZn4XNdO8UfHyGqC6nnCxlSe4Z8P88',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI5NzViNjY4OS1jMzAwLTQ1YTQtYmNiYi02MjllZjhlZmU5ZjAifQ.96alLW7hjY-KLda19O74_PxoF4VVF3e0sH-uEGmgPgI',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI5YjRmMzk2Yy0zMjQ5LTRhNzktYTU3OS02NzRjNjVjODkyZjAifQ.rQJIgHG0bZ6gnwJxzVrtdsX4xU_2b8QkC5Y0_tw7JrY',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIwYzE1YjY1NC1hZmVmLTRlMmItOTkwZS0zMjhjNDJiM2ZhNjAifQ.MnCCwUTthTrYmd5KZQBA4lhzSbI7gWOBHnrhDzn1h4A',
]


url = 'http://10.102.21.141:6600'
