
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0YWU5MDY1Ni00Yzk4LTQ2MTAtOTU3Ny0yNTY4NGIxNDllMGMifQ.sOzP15ZItZUaa8S4dLU8xUOXPIIhk8Kau4UoQF5GfCM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI2YTNkYjlhYi03YzQ3LTQ0ODItODJlZS1jNGFjY2RhZjhlY2EifQ.vXOLwerRfNzX0XkHk5TlRAXYdm3vvGVFuxaUasfrkmg',
]


url = 'http://10.102.21.141:6600'
