
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI4MWE4ODc4MS1kY2Q5LTQyMWYtYjc0NS1jZDU5YTliZDhlNDcifQ.seLsB1TIM56lRqVhu4vlOiok32Nwi1SyKzIVsxhxFCM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIzMTMzOGJhOS04ZTkzLTQwYzYtYTIwYi0xZDBmMDAwNWI1NmEifQ.V6D-kpS_pLvnnPj1zY4ouqMSoy93-jk9RDPRZ5oNfxI',
]


url = 'http://10.102.21.141:6600'
