
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI0MWU1OTI2Yi03YWU2LTQxNmMtYjIyMi0zNzI0OWNhMDQyM2IifQ.93nNuSQoVSVSOOa2KaUSOTvqqmO5QAjBKCQ4-qmyZt8',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2YTU4NjM3Mi01YTYyLTQzMTEtODY2OS0yNzAxZjhlNWRmOWMifQ.Q_d8cBKRBU1r2YDOElUbJ9ce3iIHE55USSwpfb1HLig',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJhZDlkYmI5Yy01NWRlLTRiNWQtYTI4ZS0wN2QyODk0NzQ5YzEifQ.qfP2PvdHoRqIbD_ynfJzGRsXDhC4bSEaHHRR89gGagA',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjZDJhNTU4OC1hMDkyLTRmNTctYmZlMi1mMzQxNDBmNGJiZjkifQ.ypWFc4RRU7N7ISTrdDjRVurmUJF5qy-ITr8WbM80zro',
]


url = 'http://localhost:6600'
