
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI1MTNlNGVhZi04MGQ1LTQ0NjYtOTc5ZC0wYTI1ZTliOTkyMmIifQ.DbT35wh5ecUn88aedh9Mpydt7eaThscwYoc-ub14w3U',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIwOTM4YTdhMS0xZGM1LTQwYTktYjM1OC04MzNmY2Y3NjIyYzkifQ.YREAfbUpkN7MuF2tJhCrfQUBVeJc-GuWnNtbhsAsseA',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjYjI3MDIxMC1lZTY0LTRjZGUtYjgxYS0wMTdkM2U3NWYwYTgifQ.Nz7Byo6xQ7rqn7YYX6eaF4Csu7-zEMilZB5UT4PPJio',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlY2YxOTA1Zi04MzQxLTQ3ZjItYWU1OC1jZGZmN2EwZjkyOWEifQ.qVLMm5NcTJgjB-HR6F8sCdzJUsJQcXOKCE1QT4z6110',
]


url = 'http://localhost:6600'
