
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI0ZmQ2Mjk5NC03MDc1LTRiOGYtYTkzNS0wYjQwYmVkZDVkNTcifQ.yA4e6tg_A-KyIgwNzA9zsj7T9UG9jHataq0pK3l5VP0',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2Y2FhNDk5YS1lOTIwLTQ5MzEtODA0MS1kMTRjNDc1MmNkZGEifQ.zE_vpCsvyXG7gZBmQ_Mc0kQEDxoKTPVGZJToGn8xJQg',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2ZGUxMTVkYi1jNjcxLTQzMjItYmI5Mi02ZTZhMjg3NWM3OWIifQ.EvzudzeRDIWqThEUlVKTQf0eG1omY3BcolTEIYajTTw',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2ZmUwM2I1YS0yOWUyLTQ1NjMtODA5Ni1lYTBkYTg2YjExOTcifQ.u--2vpb6LnuOVi6O0R74NPVYzK06mi0a2UD40kvF7A8',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI4MjY0NmE4Yi0zNTM4LTQyZGMtYTdkNy1hZDBlZjdiOTE5NjgifQ.PNlDMNGINahIvw-_Y98MBK_stcysRYAdD4bgeM2xSyQ',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5NGFlN2UwOS00Yzg2LTQxN2QtODdkMS0xNDQ1YTYwODE0MzIifQ.iZiOChffTGQZwMBY4cK7rgXGZShPGQlE0C2ReorbyVk',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5OTlkZmRhNy0wYzJjLTRhMDUtYjJiMy0wMTkxMjFmM2FmNDgifQ.zyjERTVutM30zjbxeJkeHj72oW7_PuxomiLG7OuoPh0',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIxODM2ZWE3Zi0xNWY2LTQ2YzktYTg3Ny03ODRmMTdjNTY2MDMifQ.G-8UYn9bwtTfyhlKOT-AS9Q7929PLjXFTihHGOquoC4',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMzdlMmIxNi1iMjZkLTRkMTgtODU1Zi02ZWY1YmVlODdkNjkifQ.qseFG1ItWH9ZgoVPJNt6ne81P1UWZyjI4BS1CPqNLso',
]


url = 'http://localhost:6600'
