
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI0NWM3MmYwNS05YTczLTQwNDQtOTI3Mi02ZDk3MzU1YTQxNjkifQ.iYxEOzYyXa5Jd6lGbUO5am8T8e7Dv2EOz-hEDwuID9Y',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2Y2FhNDk5YS1lOTIwLTQ5MzEtODA0MS1kMTRjNDc1MmNkZGEifQ.zE_vpCsvyXG7gZBmQ_Mc0kQEDxoKTPVGZJToGn8xJQg',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2ZGUxMTVkYi1jNjcxLTQzMjItYmI5Mi02ZTZhMjg3NWM3OWIifQ.EvzudzeRDIWqThEUlVKTQf0eG1omY3BcolTEIYajTTw',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2ZmUwM2I1YS0yOWUyLTQ1NjMtODA5Ni1lYTBkYTg2YjExOTcifQ.u--2vpb6LnuOVi6O0R74NPVYzK06mi0a2UD40kvF7A8',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2ZmVmZmEyOC01NDRmLTQxZDEtYjY4My1iZDRkZjBlMDFkMjIifQ.rUzg9pgwIpwoKtpHPhwiJ3bss0DcnFhGQKcV8XX_MQM',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5NGFlN2UwOS00Yzg2LTQxN2QtODdkMS0xNDQ1YTYwODE0MzIifQ.iZiOChffTGQZwMBY4cK7rgXGZShPGQlE0C2ReorbyVk',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIxODM2ZWE3Zi0xNWY2LTQ2YzktYTg3Ny03ODRmMTdjNTY2MDMifQ.G-8UYn9bwtTfyhlKOT-AS9Q7929PLjXFTihHGOquoC4',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIzOGZkYzBjMy0zMDU2LTRlN2YtOTQzNS05OTU1MmY5MzQ2ZmQifQ.9wWcqGjQr1_f7YjT1lmN4PUkT-y95JSzS05_JqpV0ug',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMzdlMmIxNi1iMjZkLTRkMTgtODU1Zi02ZWY1YmVlODdkNjkifQ.qseFG1ItWH9ZgoVPJNt6ne81P1UWZyjI4BS1CPqNLso',
]


url = 'http://localhost:6600'
