
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0MWQwYTYwMi0xNGVkLTQ1YWYtYTJhMC0yMDJjMDJmZTNhNTYifQ.ngKQZoNNWBRf3kly01qq2O6WQ6oFbY7CnhieFHHDCOM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1Y2VhZWE0NS1hMjU4LTRlZGUtODNhOC1kNDc3MDA4NDkyNzgifQ.FA-ZG7xxFXxR-PDdq_gdcjtEbPYUaaRvdc8-oo55lsk',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyMTcyY2NkMS1hMTBjLTQzYjgtOWJjOC03MTk5MWVjYjY3YTgifQ.K_sXcGFqDr324dtDQeXDXy8Yhft-w_xmcSU4q_PZdto',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyZGNiYzdiYS00NDEyLTQ5NmEtOThhOC03ZDgwYjY3NWMxNDYifQ.cjwdSVbcD2NcWlVqPHZ0ItyXW0gbjeurrFNxVwDYpNM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJiNmUxMzRlNS1mMjUwLTQxZTYtYjVlYy1kZWFlN2U0MTkwMTkifQ.2vdMAMBN9FrtQlEWSDQ0wIxNIGTscfY0bqApPfY9zm4',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMWUxOTY1My1mNjk3LTQxNWUtYWJjMi1kNjAwM2ZmZjU5ZjUifQ.K4PFl0Y_EQKz1b7iM03tl6o_OoR9yM0s-Y0fPTHm9uU',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjNzgzOWUzNi04OTdhLTRmNGEtYTBmOC1lMmNkODE3NjVhZDEifQ.ImFpthKSYMIhbbnLWqpxxwsD9Fbt_TgPif3Wmny0ZiI',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJmMTRkMzNkYS03ZjM4LTQxOTItOGE5Mi0xMGY4YTdmYzBmNmYifQ.nedzEoVjERNa0_KGJtbm3383L7ahb12fMo1jQNb3AQ0',
]


url = 'http://localhost:6600'
