
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI1NDdhOWJlYS0xMDc0LTRiYzUtYmUzMi1hNjQ5NDc4MTAzN2YifQ.mhG5O8cljKJ0_GhoJe4ZWKBkl1mWmDwJiDhScPhYYAc',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2MzM5YjYzOC0yMGVhLTRlZWEtYWJjYS1iNWQxOWVlYWM5MTgifQ.pKyybvCsnX-gHw12ZZuIwYUdascyWoED_dLw0cyeN00',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIyZjJiMDE0NS01MDE2LTQ0NDQtYjJkMC0wOWM0MzIwODk2YjgifQ.00NBG7YcZO04NICsrtMqkhq6BJWUsfBECz8yZjjUjqg',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlNDYyZTg0ZS03NDc0LTRkMDAtODBhNy1lZDkyMWI2YTM5ZDQifQ.t9rG5rpoWkHA6A2mmgzvYscw6NBwz-ckqL1NKbj1bcA',
]


url = 'http://localhost:6600'
