
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIyZjJiMDE0NS01MDE2LTQ0NDQtYjJkMC0wOWM0MzIwODk2YjgifQ.00NBG7YcZO04NICsrtMqkhq6BJWUsfBECz8yZjjUjqg',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlNDYyZTg0ZS03NDc0LTRkMDAtODBhNy1lZDkyMWI2YTM5ZDQifQ.t9rG5rpoWkHA6A2mmgzvYscw6NBwz-ckqL1NKbj1bcA',
]


url = 'http://localhost:6600'
