
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0OGQxZmVkYy0yZDQ0LTRjNmQtOWEwYi04MjI2MjU0N2ZhZWQifQ.MZsR7MLwFxxyETwGXh3pu_w-1a4GohI328gXSG_t1cc',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIwMDg1MTc4Ny0zM2Q3LTQyYTEtYWI2Yi0xNTU5ZDBjYjVkNTkifQ.H-RPuD48g8h4Gp0VIi66c9oTd-TVtiBQC2mw_DDZlJA',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyM2Y5N2QzZS0zNzkzLTQ0NTctYmIwYy1hYWQ0ZjYwNDhiMTMifQ.IL4bPUxn90V83R5z-NG1NeHi211m6xoSFpQaMNdAGXk',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJhMzZjMzExMC0yYjFkLTQ5ZWUtOWQ0ZC1kNmRjZWVjZTliOTAifQ.v8HQ2TX-LwkPU2gekU0qvsY3O346I8C7YtAh7YBpE3o',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJiMjM4ODE1Zi04MmI4LTRiYmYtYWVlMS1iMjUwNTdiYzUxNDIifQ.Px2ntaHJOULAZeNicABE20DH-w_yRjImyDL3Q7AzIJI',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjNmJkZDFlNS02YjU1LTQ5YmEtYjY3NC0zN2RiYmI2M2E0NWIifQ.lyheCgN1-7zzjdKP5xvWHEch9nrpHbF9ETePCYUIT-U',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJkNzVkOTAyMy1jNTYyLTQ5ZTUtOTZhMy02ZmI0ZTE3OTkwN2IifQ.cVKd6ILstZiXVHi2S97ljiaT8lpPETg8x7q2mfIl2Fc',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJlMjE0ODk2ZS00N2E2LTRmYjYtYTMyZC0zMzllODUzNDdjYWMifQ.6-uQROxeXqI0BD7GPi4UnvUYYMVGY8TgGFRbnzCC2pQ',
]


url = 'http://localhost:6600'
