
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0MWQwYTYwMi0xNGVkLTQ1YWYtYTJhMC0yMDJjMDJmZTNhNTYifQ.ngKQZoNNWBRf3kly01qq2O6WQ6oFbY7CnhieFHHDCOM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0ZTU0MzEyMS1jZWYwLTRmYjEtOTA1OC0yMTRkMWQxOTEwYjIifQ.P20G-UiAJrC0ISsyxavo6zcqo6SDCzrkZ8wDxPReQJg',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1MWFlODBjNC02ZmI0LTQ0YmUtOGE1NC00MzM4OTE3MWI4ODAifQ.ChJi87BxAxLe6ox6X9kPBzmWZLXzpZIF96jt3OvJmOM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1ZDIwMWI3Yy1jNzM5LTRhODUtOTcwNy02OGMxYTY0NmUxMjAifQ.sfy7zIYAZsX4HjgS4-V4a4Bkwtu8Cy1YnQ-Bnn61cd0',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI5OTgzNDNhNy1jZGQ0LTQ0ODItYTRlMy0xM2IyMDhkNmU4NzMifQ.Hj7GHk5ncCOAPN_VnXr1LH_6bRx3F5Ukx6kMG0IQ2BQ',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIxOGJiMDBlNC1hZmRhLTRjODYtODkyOC03MzFkOWM4ZTE0YzIifQ.bulMENmsSrjXnMdvS9JWk8HoHEkRwCvcgCL7oArH_so',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIxZjAxOGE5Ny1mNGQxLTRjYzctYWQxYy03NjhkZGQ3M2NhYzEifQ.UcoN74fIdAmw-xu3OxzkA5469pIiO6ZTzqZ8nFRFCXM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyMTcyY2NkMS1hMTBjLTQzYjgtOWJjOC03MTk5MWVjYjY3YTgifQ.K_sXcGFqDr324dtDQeXDXy8Yhft-w_xmcSU4q_PZdto',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyZGNiYzdiYS00NDEyLTQ5NmEtOThhOC03ZDgwYjY3NWMxNDYifQ.cjwdSVbcD2NcWlVqPHZ0ItyXW0gbjeurrFNxVwDYpNM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjNzgzOWUzNi04OTdhLTRmNGEtYTBmOC1lMmNkODE3NjVhZDEifQ.ImFpthKSYMIhbbnLWqpxxwsD9Fbt_TgPif3Wmny0ZiI',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJkMDk5OTMyMC03YjYzLTQ1ZmUtYTg3Zi1lMTYwM2IzMWMxY2MifQ.UKR17yykAXtLEwanC0oqeJSjCbR7wE5zt6HdeKiKPlw',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJlODdjOWM4Ny1iMDQ0LTRkOTEtYjM3Yy1lZjA3N2E2ZWViNzIifQ._uMwHKRQWe3SOTqgdFWDAMQFU86VJBNrBFMo7U2dT2E',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJmYTI2YTQ0YS0wZGEwLTRlMjEtOThhMS1lNDZlM2Q5NTlhYjkifQ.Ug2Av2d4hvXvZ60j4KCcqddhu2mGiWmPO73fR12k-IM',
]


url = 'http://localhost:6600'
