
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI4NGQwNzcwNC02ZTI0LTQ3YTktYjllZi03NjI1NTE1NDc0YWQifQ.OqcBNCJpQ8yMS0j3f638bG5YzZFZkDnHWAgCtaBIaBk',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5YTY4MWNjZi0yZDJiLTRmZDAtOGZiNy1jMGYzNWRiMDA3ZTAifQ.FMnIqHQJa2qEM0WZqb7NQmr_HNTAceh8t1q3O8LlDHY',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5YzBlNDJiNS0zYWVlLTRhYjMtODgyMy1hM2QxMDdmNDc4MTkifQ.xRSktwSzXF-HNoJtstYubB3ONS2mf9cua1rkY14U77g',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIzNmVjMDNlMC02NjYyLTRkZDAtYThlMC1kYjFmNWE3NTU5OWYifQ.vUDt0NV5rvkjHGmPUCH4t_IfzyUbK2aKl1xNrnZ-I74',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlMGZhMmUwZi0yOGY3LTQyZGItYjUyYy1jYTAwMzEyYWVmNzQifQ.aCEgTmpB9gFydDvGDYmWJmT37a7yoJLjOIsaBDDkoPQ',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlNzc3NTgzMy0xYmFlLTQyZmYtYmM1ZS0xNGMyMmQ3MDk3ZjYifQ.Cd9VfxFzNs1M4U_3yQvNULX0nZzxz8EnfbaqROaGyRY',
]


url = 'http://localhost:6600'
