
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI0NjFjYTcxNy0xODY2LTQyOTUtOGI0NS1mOWQ5NGM0OTc0YzgifQ.A0vudc6CkPTOA3hQ3SvUlfL94nqYK8nvBlWcAfybY_U',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI0YjkyMTQ4MC0wNjM1LTQ1NjQtYTdjYy0wMWYwMjUyZDk0M2EifQ.Jni-nemCPnpM_fPMxZ99eWGvuS8xxEJdqt4cKz0X1R0',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI3ZTRiZjgwNy05NWYwLTQ0MjAtYmEyMC03ZjQ5NGY0OTM4YTEifQ.h87D-M8Wg4Jiw8iR43_iwvNVA4b3zeL8LqnVZbXisGs',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI4NGQwNzcwNC02ZTI0LTQ3YTktYjllZi03NjI1NTE1NDc0YWQifQ.OqcBNCJpQ8yMS0j3f638bG5YzZFZkDnHWAgCtaBIaBk',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5YTY4MWNjZi0yZDJiLTRmZDAtOGZiNy1jMGYzNWRiMDA3ZTAifQ.FMnIqHQJa2qEM0WZqb7NQmr_HNTAceh8t1q3O8LlDHY',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5YzBlNDJiNS0zYWVlLTRhYjMtODgyMy1hM2QxMDdmNDc4MTkifQ.xRSktwSzXF-HNoJtstYubB3ONS2mf9cua1rkY14U77g',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIzNmVjMDNlMC02NjYyLTRkZDAtYThlMC1kYjFmNWE3NTU5OWYifQ.vUDt0NV5rvkjHGmPUCH4t_IfzyUbK2aKl1xNrnZ-I74',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJiYTUyZmEwOC03ZGFkLTQ1NjAtYTI1ZC00Mjg5ZDA4NGRkMWYifQ.-mz94XzQnbvHURhRYYkw8pKwhPFczVxqK3fWgS1Fbu4',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjN2JiNjUxZC1mYTdkLTQ1OGItODU1ZC1iMzM1NTk2ZjQ3YjMifQ.U0lZfX7z8_YxqFCeAbl33KBQZaam1QZVWNATzIzJMg0',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlMGZhMmUwZi0yOGY3LTQyZGItYjUyYy1jYTAwMzEyYWVmNzQifQ.aCEgTmpB9gFydDvGDYmWJmT37a7yoJLjOIsaBDDkoPQ',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlMjE3MDM1ZS05NGMwLTQ5ZmEtODllNi01YmM4ZjU5MjQxZmEifQ.AyyFg9yucgl4nhhANClp29ClMeXPvwP5FX_-LRtH0tg',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJlNzc3NTgzMy0xYmFlLTQyZmYtYmM1ZS0xNGMyMmQ3MDk3ZjYifQ.Cd9VfxFzNs1M4U_3yQvNULX0nZzxz8EnfbaqROaGyRY',
]


url = 'http://localhost:6600'
