
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI3N2RkN2E2Ni1lZDllLTQ4NzktYjM3Yy1kZDk1NzIwZTFhMWEifQ.N8EG11ZqMlL7GBy576167zPgfseaNp63igN8FR2nEec',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIzYmQxMWFiZC1kMDA5LTQ4ODYtYWY2Ny0zN2QxYWVlYWE4ZDAifQ.PO4s_DwH2i1Iz36sOtcml6eHeosGTYKZ2irGacLvVAY',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMDEwNGY5Yy0xYjUyLTQxMWItODE3Yi1hZjY4ZThiNTBlMjEifQ.iyZg5t09eAttsD-QErAql8cPcpyVyXHv7pkvtd3YY8M',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjYzM4MWRkOS0zNzY5LTQ3Y2EtOGE3ZC04MzkyZGFlYjc5NjYifQ.Mf3rC-DS1kt0B9JGsA-Wot1KAHYJZEsp8FLjVReiFIE',
]


url = 'http://localhost:6666'
