
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0MWQwYTYwMi0xNGVkLTQ1YWYtYTJhMC0yMDJjMDJmZTNhNTYifQ.ngKQZoNNWBRf3kly01qq2O6WQ6oFbY7CnhieFHHDCOM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI1ZDIwMWI3Yy1jNzM5LTRhODUtOTcwNy02OGMxYTY0NmUxMjAifQ.sfy7zIYAZsX4HjgS4-V4a4Bkwtu8Cy1YnQ-Bnn61cd0',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIxZjAxOGE5Ny1mNGQxLTRjYzctYWQxYy03NjhkZGQ3M2NhYzEifQ.UcoN74fIdAmw-xu3OxzkA5469pIiO6ZTzqZ8nFRFCXM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyMTcyY2NkMS1hMTBjLTQzYjgtOWJjOC03MTk5MWVjYjY3YTgifQ.K_sXcGFqDr324dtDQeXDXy8Yhft-w_xmcSU4q_PZdto',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyZGNiYzdiYS00NDEyLTQ5NmEtOThhOC03ZDgwYjY3NWMxNDYifQ.cjwdSVbcD2NcWlVqPHZ0ItyXW0gbjeurrFNxVwDYpNM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjNzgzOWUzNi04OTdhLTRmNGEtYTBmOC1lMmNkODE3NjVhZDEifQ.ImFpthKSYMIhbbnLWqpxxwsD9Fbt_TgPif3Wmny0ZiI',
]


url = 'http://localhost:6600'
