
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2Y2FhNDk5YS1lOTIwLTQ5MzEtODA0MS1kMTRjNDc1MmNkZGEifQ.zE_vpCsvyXG7gZBmQ_Mc0kQEDxoKTPVGZJToGn8xJQg',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI2ZGUxMTVkYi1jNjcxLTQzMjItYmI5Mi02ZTZhMjg3NWM3OWIifQ.EvzudzeRDIWqThEUlVKTQf0eG1omY3BcolTEIYajTTw',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI5NGFlN2UwOS00Yzg2LTQxN2QtODdkMS0xNDQ1YTYwODE0MzIifQ.iZiOChffTGQZwMBY4cK7rgXGZShPGQlE0C2ReorbyVk',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIxODM2ZWE3Zi0xNWY2LTQ2YzktYTg3Ny03ODRmMTdjNTY2MDMifQ.G-8UYn9bwtTfyhlKOT-AS9Q7929PLjXFTihHGOquoC4',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIxYzNmNDBlOS1jYTZmLTQwM2EtYjFjOS0zOWQwMTdkZGVmNDAifQ.OTAf-USBcKibaCooiph5sOMWmDpTc6ue3jIsZ7AcokE',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMDYzM2IyMy04ZTU0LTRiY2UtYjk5YS1iZTYwYWFjY2VlMTQifQ.GCnzGPmgC4hVXdqoPL8VJi3MAI5pMRmLGzyYk1wto-E',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMzdlMmIxNi1iMjZkLTRkMTgtODU1Zi02ZWY1YmVlODdkNjkifQ.qseFG1ItWH9ZgoVPJNt6ne81P1UWZyjI4BS1CPqNLso',
]


url = 'http://localhost:6600'
