
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI1ZDAzZDMzYy1iYWI3LTQ3YjktYmUwOC1hYjhmZjIxZTFhNWMifQ.YDJChp6mlNYlG7kFc2sB7gTvhKV0tSS1vkMJoErd3_E',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIyYmExNTBhZS01MDZjLTRkOGYtYWI5NS03NTUzMTgyNjdmNDIifQ.dLfZfo8uPpOUjmzYu6ieO3uUFkraosdBw1lrsuaQjV4',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0YmUxMDg3YS0zZGQ0LTQ2ZjMtODZmNy1mMmFlZmMyYTc3YTMifQ.A2rcZ1BDMO62GPsnj3mGbiAmoEXiSUTPxqFDapv8yCs',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0ZjlmNTg1YS1jOWNmLTQ1OGQtODhkZS1mMzg3Y2JjMjAzY2IifQ.JfuXcJY3-noXELBVZpKujeD_CuBBxFsVXQhLzjZ5Xgc',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI3YTU4MjY5MC1mNjc4LTQ2NzgtOGQ0MS03YzIzMzYyOWJmY2YifQ.h8q7TFs-9UcZPgkVHjl3HmpmKQnmp7BZK-464qXR32Y',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI5ODMzYzA4Yi1hYWE4LTQ1ZDQtODNiZC1mZDY0ZWIxMTY1YTMifQ.uM44Ot3BEyWcE8L6I8iAf0Ei5Sv7VeOeswd85ptjkMA',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIxYWViNjA2Ni05NGVjLTRlMGYtYTc3Ny0zODZkOTcyYjFmMmIifQ.ZeutwVYAJFfdK5jfYdi3lxE5wUbVYROIi2rkK2yN594',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIzYTllNjM2ZC1lZjY0LTRiMjUtYjFhMi1lYWU2MDg1N2E0ZjAifQ.Pn-0axofWf_IlVylysEkUXK9bjw5bd0-HKWDEWQcmE4',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJiMTk3MmQ5MC1jYTNhLTQ1OTUtYjk2OS1jOGIxMDYxOGRhYTIifQ.g3GSbKaQlwHUTpB_hPJtZfwM_k8BO4RZxdEQwSFo3w8',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJiOTRhNTExYy1jNzM1LTRmM2YtOTEwOC1kYTNkYmU5ZWVjNzEifQ.fki3ogJQtGHdY-vQKjPiQea0kudASxWae9dRJRpKI7Q',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJmYTdjYWU2Yy03NzRkLTRkNTYtOTRmYS00OGZjNzYyMGM1NTcifQ.HWZUZsd8J2Ih6mc9EQwsfyXS8UDlZDUI-PYRimyN7sw',
]


url = 'http://localhost:6600'
