
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI0MWQwYTYwMi0xNGVkLTQ1YWYtYTJhMC0yMDJjMDJmZTNhNTYifQ.ngKQZoNNWBRf3kly01qq2O6WQ6oFbY7CnhieFHHDCOM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyZGNiYzdiYS00NDEyLTQ5NmEtOThhOC03ZDgwYjY3NWMxNDYifQ.cjwdSVbcD2NcWlVqPHZ0ItyXW0gbjeurrFNxVwDYpNM',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjNzgzOWUzNi04OTdhLTRmNGEtYTBmOC1lMmNkODE3NjVhZDEifQ.ImFpthKSYMIhbbnLWqpxxwsD9Fbt_TgPif3Wmny0ZiI',
]


url = 'http://localhost:6600'
