
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiI1MmIyMDMxYi0xZDFiLTRiOTItYmNjNi1iZDZmMmNlMTNlYjMifQ.CIuH1YKuxnWhztdnpt3_FMEejGqSJOWRoHSR5jP9rm4',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiIxMmVlMjk1YS1kMzYwLTQzZGMtYmFmYi05ZDcyOTc0MDc1NDQifQ.TqQh-2PCiv0ivJpOFrdyQ4a-0Ne-N6HXnQNCTUh_R-8',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJiZmUxY2I3My04MGM2LTRlMWQtODhlNS1iOGU0YTk5NTk3NTAifQ.iwHcpWwqTq57P2QhXG5M9JfPvBWSi_sQveVpTx7U8zs',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjMDRjMTRmOC03MTQ4LTQ5NDgtOGVhMi02ZTZiMDQ3ZDIxMGUifQ.CxNYYUwsBDtMo86elNF5aXs4YXG-msHLQznslMOIs3M',
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzZXJ2aWNlX2d1aWQiOiJjYzlmYmIyNC05MmJhLTRhNmYtOTRhYi04NTdmZTY2ZGUzYmQifQ.Fi1TCaRQ-aoDZH_DLKbTr0PCiiAviM4Z_fzJAuTsY1g',
]


url = 'http://localhost:6600'
