
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjYjQwODAxMy1jMWJlLTQ3YjUtODE0MS03Njg0M2U3OTUwNTUifQ.jnQs71NzKc29dCX56afLgtotTeCFDBNNfLm7geln-JY',
]


url = 'http://localhost:6600'
