
god_token_ = ''

jwt_ = ''

secrets_ = [
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiI4Mzk2ZTFkMi0wYTMwLTQwMzItODg0Yy1kZWQ2Y2ZlNWU5ZTcifQ.8lMD9Wo-4TtrNs3z81i2IEqWoEhIQRII2QVc1R39gL8',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiIyOWI5ODA3MS1kYjExLTQ2ZTgtYTY3NC1jZTI1YTQyZmNjNDUifQ.B4M6rYQE4D3Zggga-s-6sif6dPwDgZeecIRCUCysPkQ',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJjYjQwODAxMy1jMWJlLTQ3YjUtODE0MS03Njg0M2U3OTUwNTUifQ.jnQs71NzKc29dCX56afLgtotTeCFDBNNfLm7geln-JY',
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXJ2aWNlX2d1aWQiOiJmODIyMTJlYi1kYjgxLTRlYzctYWY5Zi1lODRkYmExYmE3ODYifQ.OebYPdY8pPO6tGcAs_OwUz1BfqZwjNpsqA1z2tTIbzE',
]


url = 'http://localhost:6600'
